# @baseUrl = http://localhost:8080/api
@baseUrl = https://api.topgiaovien.vn/api

GET {{baseUrl}}/vip/users HTTP/1.1
content-type: application/json

###
GET {{baseUrl}}/vip/homes HTTP/1.1
content-type: application/json

###
GET {{baseUrl}}/vip/tuyen-dung HTTP/1.1
content-type: application/json
###
GET {{baseUrl}}/vip/share HTTP/1.1
content-type: application/json
###
GET {{baseUrl}}/vip/share-post HTTP/1.1
content-type: application/json
###
GET {{baseUrl}}/vip/teacher HTTP/1.1
content-type: application/json

###
GET {{baseUrl}}/vip/course HTTP/1.1
content-type: application/json
###
GET {{baseUrl}}/vip/time HTTP/1.1
content-type: application/json