# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["release-v1"]
  pull_request:
    branches: ["release-v1"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass
        

        
      - name: Install dependencies
        run: npm install --force
        working-directory: ./client

      # Build project
      - name: Build project
        run: npm run build
        working-directory: ./client
        
      - name: Verify dist content
        run: ls -la client/dist

      - name: Kill tmux
        env:
          SSH_FINE_FINISH_PASSWORD: ${{ secrets.SSH_FINE_FINISH_PASSWORD }}
          SSH_FINE_FINISH_USER: ${{ secrets.SSH_FINE_FINISH_USER }}
          VPS_FINE_FINISH_HOST: ${{ secrets.VPS_FINE_FINISH_HOST }}          
        run: |
          sshpass -p "${{ secrets.SSH_FINE_FINISH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_FINE_FINISH_USER }}@${{ secrets.VPS_FINE_FINISH_HOST }} "
            tmux has-session -t client 2>/dev/null && tmux kill-session -t client || echo 'No tmux session to kill'"

      - name: Deploy via SSH
        env:
          SSH_FINE_FINISH_PASSWORD: ${{ secrets.SSH_FINE_FINISH_PASSWORD }}
          SSH_FINE_FINISH_USER: ${{ secrets.SSH_FINE_FINISH_USER }}
          VPS_FINE_FINISH_HOST: ${{ secrets.VPS_FINE_FINISH_HOST }}          
        run: |
          sshpass -p "${{ secrets.SSH_FINE_FINISH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_FINE_FINISH_USER }}@${{ secrets.VPS_FINE_FINISH_HOST }} << EOF
            echo "Cleaning and preparing dist directory"
            rm -rf /root/topgiaovien/client/dist/*
            mkdir -p /root/topgiaovien/client/dist
          EOF
            
          sshpass -p "${{ secrets.SSH_FINE_FINISH_PASSWORD }}" scp -o StrictHostKeyChecking=no -r client/dist/client/* ${{ secrets.SSH_FINE_FINISH_USER }}@${{ secrets.VPS_FINE_FINISH_HOST }}:/root/topgiaovien/client/dist
      - name: Restart application on VPS
        env:
          SSH_FINE_FINISH_PASSWORD: ${{ secrets.SSH_FINE_FINISH_PASSWORD }}
          SSH_FINE_FINISH_USER: ${{ secrets.SSH_FINE_FINISH_USER }}
          VPS_FINE_FINISH_HOST: ${{ secrets.VPS_FINE_FINISH_HOST }}
        run: |
          sshpass -p "${{ secrets.SSH_FINE_FINISH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_FINE_FINISH_USER }}@${{ secrets.VPS_FINE_FINISH_HOST }} << EOF
            echo "Connected to VPS"
            cd /root/topgiaovien
            echo "git reset"
            git reset --hard HEAD
            echo "git pull"
            git pull
            echo "node install"
            cd client
            npm install --force
            echo "deploy"
            tmux new-session -d -s client 'npm run preview'
            echo "success"
          EOF
